galaxyproject/ansible-galaxy

- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
Minor fix to make role name match ansible
> Change role names to match ansible galaxy

- tasks/dependencies.yml
ping @drosofff, who asked about this on gitter.
> Fix pypi index url

- files/makepyc.py
- tasks/dependencies.yml
Adding parentheses in 2 locations is enough to use role under Python 3.
> Update print statement syntax to support Python 3.

- README.md
Assignment vs. equality ('=' vs. '=='), see Jinja syntax.
> Fix syntax error in sample code (under Requirements)

- tasks/database.yml
Reports the current and maximum database version before upgrading database.
Uses `clone.yml`'s report style.
> Added report for current and max database version

- README.md
- defaults/main.yml
- tasks/layout.yml
- tasks/static_setup.yml
- templates/local_tool_conf.xml.j2
- vars/layout-custom.yml
- vars/layout-legacy-improved.yml
- vars/layout-legacy.yml
- vars/layout-opt.yml
- vars/layout-root-dir.yml
> Support for installing local tools and dynamic job rules from the playbook

- tasks/dependencies.yml
- tasks/virtualenv.yml
Added extra args parameter to allow passing custom parameters such as --compile and --no-cache-dir to pip.
> Added pip_extra_args parameter

- README.md
- tasks/dependencies.yml
- tasks/virtualenv.yml
> Replace: pip_virtualenv_command > galaxy_virtualenv_command

- README.md
- filter_plugins/uwsgi_yaml.py
The syntax is not ideal, but it's the best I came up with. Ideas welcome.
Fixes #66.
> Support uWSGI config ordering and logic blocks

- meta/main.yml
https://github.com/galaxyproject/ansible-galaxy/blob/master/tasks/layout.yml#L26
Discovered when it was unexpectedly unset for @gmauro when he tested the training.
> Update minimum version.

- defaults/main.yml
- tasks/mutable_setup.yml
- templates/shed_tool_conf.xml
xref https://github.com/galaxyproject/training-material/pull/1445
does this look ok? untested because internet.
> Template out shed tool conf more better

- .travis.yml
- README.md
- tasks/virtualenv.yml
xref: https://github.com/CloudVE/galaxy-docker-k8s/pull/10
> Added support for python 3

- defaults/main.yml
- tasks/_inc_client_build_steps.yml
@dannon does this look right?
Fixes #88
> Support deconstructed client build on > 19.09

- README.md
Addresses comment: https://github.com/galaxyproject/ansible-galaxy/pull/91#discussion_r339604847
> Minor clarification in readme

- .gitignore
- filter_plugins/uwsgi_yaml.py
(I highly doubt it can handle line wraps)
> Set an arbitrarily long width for uwsgi YAML line lengths

- tasks/main.yml
xref https://github.com/galaxyproject/ansible-pulsar/pull/7
> Swap undefined `ansible_user` to `ansible_user_id`

- .travis.yml
- README.md
- defaults/main.yml
- tasks/clone.yml
- tasks/compile.yml
- tasks/download.yml
- tasks/existing.yml
- tasks/main.yml
- tests/test_playbook.yml
Supercedes: https://github.com/galaxyproject/ansible-galaxy/pull/117
Corrects PR branch
Adds ansible version patch
Factors out compile step
> Added support for using an existing Galaxy folder

- tasks/_inc_node_version.yml
- tasks/main.yml
This is mainly to aid PR: https://github.com/galaxyproject/galaxy/pull/11161
> Propagate tags to included tasks and allow client build to be executed independently

- defaults/main.yml
- tasks/clone.yml
This can be enormous if you have not recently updated Galaxy.
> Add option to suppress large diffs when Ansible diff mode is enabled

- tasks/static_setup.yml
following the advice in https://stackoverflow.com/questions/68637451/ansible-regex-search-unknown-escape-character
> Try to fix "found unknown escape character" in #141

- defaults/main.yml
- tasks/static_setup.yml
the name of this option is without the s in the word "container"
https://github.com/galaxyproject/galaxy/blob/5846886edb176d072a5043c6abf1777d756fc5c0/lib/galaxy/config/sample/galaxy.yml.sample#L500
> fix a typo in the name of the option

- .github/workflows/ci.yml
- .gitignore
- README.md
- defaults/main.yml
- handlers/main.yml
- meta/main.yml
- tasks/clone.yml
- tasks/dependencies.yml
- tasks/gravity.yml
- tasks/main.yml
- tasks/paths.yml
- tasks/static_setup.yml
- tasks/systemd-galaxy.yml
- tasks/systemd-mule.yml
- tasks/user-facts.yml
- templates/galaxy.yml.j2
- templates/systemd/galaxy.service.j2
- tests/test_playbook.yml
Also, support systemd user scope (`systemctl --user ...`).
Also fixed #137.
> Support for running Galaxy from systemd using Gravity (galaxyctl)

- templates/galaxy.yml.j2
Remove duplicated gravity section
> Added gravity to section check for galaxy.yml

- tasks/paths.yml
- tasks/static_setup.yml
> Altered group for privsep dirs to allow galaxy_user to read

- README.md
- defaults/main.yml
- tasks/cleanup.yml
- tasks/main.yml
We could add `pgcleanup.py` here as well.
> Add options for cleaning up jobs/tmp dir

- tasks/systemd-reports.yml
Just a small fix for the systemd reload handler name
> Fix handler name

- templates/systemd/galaxy-reports.service.j2
- templates/systemd/galaxy.service.j2
> systemd: delay galaxy startup

- .github/workflows/molecule.yml
- handlers/gravity_22.05.yml
- handlers/gravity_23.0.yml
- handlers/main.yml
- tasks/gravity.yml
xref: #80. Thank you @natefoo for the suggested fixes. They did resolved the issue I ran into.
> Adjust for recent gravity changes

- defaults/main.yml
I forgot to add the basedomain to the `themes_config_file_by_host`
> Fix Basedomain theme file

- tasks/static_dirs.yml
Fixes https://github.com/galaxyproject/ansible-galaxy/issues/204
> fix typo for subdomain themes

- tasks/static_subdomain_dirs.yml
should close 
- #213 
- https://github.com/usegalaxy-eu/issues/issues/500
(I can not test this currently, because my test instance is not working, so I would ask you to double check the syntax, please 🙏🏼 )
> Only omit rsync, if Galaxy is not being updated

- tasks/static_subdomain_dirs.yml
that should have been obvious.. 🙄
> fix welcome stat task

- .github/workflows/release.yml
- .github/workflows/slugger.yml
I already fixed the api key in secrets
> fix the name of the pypi package
