galaxyproject/ansible-galaxy

defaults/main.yml, tasks/clone.yml, tasks/download.yml, tasks/main.yml, tasks/virtualenv.yml
Until we have debs this is... a... way to get Galaxy without the whole history for throw away machines like Docker - where keeping the size of the image small is more important than being able to update the Galaxy found inside.
=> Implement option to download Galaxy (instead of cloning it).

meta/main.yml
By default, Ansible will only run a role once, no matter the number of times it occurs as a dependency. This makes this role difficult to use as a building block in creating more complex roles, for instance packaging the example in the readme as a self-contained role (separating mutable config and files from code and the like.
By setting the allow_duplicates option, as detailed in the [Ansible docs](http://docs.ansible.com/playbooks_roles.html#role-dependencies), the composibility of the role is increased.
=> Add allow_duplicates to role metadata

README.md
Simple typo, but caused me a bit of frustration!
=> Fix typo in config variable in README.

defaults/main.yml, tasks/dependencies.yml
Since pip seems to be evolving rapidly as of recent. 
Otherwise we're getting the [import errors](https://travis-ci.org/ARTbio/ansible-artimed/builds/104456943#L1663) on new instances.
=> Fix pip at 8.0.0

README.md
Invoking "apt" only once while using a loop via squash_actions is
deprecated. Use list of items as name value instead.
=> Update deprecated syntax

README.md
**Edit 1:** add ```become: yes```. Solves permissions issue in the advanced playbook sample code:
`postgresql_conf_dir` is set to `/etc/postgresql/[version]/main` (in
vars/[os-family].yml, which requires privilege escalation.
**Edit 2:** change dictionary duplicate keys (mule) to sequence. 
*Note: this was supposed to be 2 separate PRs. Sorry, github's UI confused me.*
=> Edits to sample code/advanced playbook in README (dupl. keys + become: yes)

README.md
As referenced by @ic4f in issue #42, the example stating:
```yaml
mules:
- mule: lib/galaxy/main.py
- mule: lib/galaxy/main.py
```
Is incorrect and should rather be:
```yaml
mule:
- lib/galaxy/main.py
- lib/galaxy/main.py
```
This appears to work correctly.
=> fix mule in advanced example in README.md

tasks/virtualenv.yml
Add virtualenv_python parameter to pip module in virtualenv.yml.
Rationale: if this parameter is not specified, on some systems Python 3
will be used instead of the required Python 2.
According to Ansible's docs, "When not specified, the Python version
used to run the ansible module is used" (pip module). However,
reagadless what Python executable is used to run Ansible, the pip module
will [call virtualenv](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py#L487)
*without* the ```--python``` option, thus causing virtualenv to use
["the interpreter that virtualenv was installed with."](https://virtualenv.pypa.io/en/latest/reference/#cmdoption-p),
which could be Python 3 (as was the case with my local system).
=> Indicate Python version used for creating virtualenv

defaults/main.yml, tasks/download.yml
Updated `galaxy_download_url` to correct path. e.g.,
- From: `https://github.com/galaxyproject/galaxy.git/archive/release_18.05.tar.gz`
- To:      `https://github.com/galaxyproject/galaxy/archive/release_18.05.tar.gz`
Added `makepyc.py` task which comes from `clone.yml`.
Replaced bash which downloads Galaxy and creates a receipt with Ansible modules.
- In this version `galaxy_server_dir` is not removed. Directory removal was not added because, `clone.yml` does not remove the directory.
=> Updates for download.yml

tasks/main.yml
Previously `galaxy_manage_clone` and `galaxy_manage_download` could be set to true and only clone would run. This PR forces that scenario to fail and tells the user why.
=> Forces users to only set either clone or download tasks to true

.travis.yml, README.md, defaults/main.yml, tasks/clone.yml, tasks/database.yml, tasks/dependencies.yml, tasks/download.yml, tasks/errordocs.yml, tasks/layout.yml, tasks/main.yml, tasks/mutable_setup.yml, tasks/paths.yml, tasks/static_setup.yml, tasks/user.yml, tests/test_playbook.yml
This should further simplify using this role to perform a "best practices" deployment and get rid of a bunch of `pre_tasks` that were required for such a deployment. It should no longer be necessary to run this role more than once.
Sorry for even more new vars @erasche :sweat:
=> Add optional superuser features for managing users, paths, and privilege separation

tasks/client.yml
Hi,
Here's a little patch to fix a problem found while updating https://github.com/galaxyproject/planemo-machine: as galaxy is installed from a downloaded archive, the client generation failed.
My artistic level in ansible is not very high, so let me know if there's a better way to do it!
I will make a PR for planemo-machine soon
=> Fix client generation when galaxy was installed from archive

tasks/_inc_galaxy_version.yml, tasks/mutable_setup.yml
=> Don't attempt to instantiate mutable configs from samples on >= 19.09.

defaults/main.yml, tasks/_inc_node_version.yml, tasks/client.yml
I also considered that we could just commit `client/.node_version` to old release branches, but then existing deployments would need to update Galaxy for this role not to fail if they updated the role.
=> Automatically set galaxy_node_version

tasks/client.yml, tasks/clone.yml, tasks/database.yml, tasks/dependencies.yml, tasks/download.yml, tasks/errordocs.yml, tasks/main.yml, tasks/mutable_setup.yml, tasks/paths.yml, tasks/static_setup.yml, tasks/user.yml
Even if you weren't using privsep mode, the use of `omit` when `galaxy_remote_users.*` were unset meant that Ansible would attempt to connect without any remote username, even if one was set or configured at a higher level.
=> Fix blanking of remote/become user by privilege separation vars

.travis.yml, defaults/main.yml, tasks/_inc_client_build_make.yml, tasks/_inc_client_build_steps.yml, tasks/client.yml
This adds some transparency for the admin but requires us to synchronize with the client build scripts and will be complicated by differences across versions. Because of that, the default is still to invoke `make client-production-maps`.
=> Deconstruct client build process

README.md, defaults/main.yml, tasks/clone.yml
Can't commit the changes @natefoo recommended to #74 so opening a new PR.
In my testing for planemo-machine it was faster to just download a tarball and then we wouldn't need to clean it up git stuff after (https://github.com/galaxyproject/planemo-machine/blob/master/group_vars/all#L29)... but that is a bigger change.
=> Clone depth 

README.md, defaults/main.yml, tasks/clone.yml
Specifying the depth speeds things up quite a bit. Have left the defaults as is to clone the entire history.
=> Allow clone depth to be specified

README.md
`python-pip` is not a dependency of `python-virtualenv` in recent Ubuntu.
=> Explicitly require `python-pip` on Debian family

README.md
A small note in the docs to clarify how to add `config/*.xml` files through this ansible role.
=> Complements explanation for config files setup.

defaults/main.yml, tasks/static_setup.yml
Galaxy 19.09 has changed how it installs "default" files, breaking the Ansible install. This PR aims to fix that.
=> Fix handling of files that are not longer present in Galaxy 19.09

README.md, tasks/virtualenv.yml
This would impact galaxyproject/training-material#1659.
cc @hexylena
=> Default to omitting the virtualenv command, and don't force it to follow the format `python...`

defaults/main.yml
Per discussion in https://github.com/galaxyproject/ansible-galaxy/commit/a0e933dd1f6422dfca66b5680fd91a717ee52836, this could be a better option for us where we're less likely to miss something.
That said, we lose the nice "cache" distinction. @natefoo what do you think. This is obviously without any migration path, and I can guess how you feel about that, likewise I don't want the mutable dir to suddenly double in size due to 2x copies of cache data.
=> Supply data_dir instead of individual cache dirs

tasks/paths.yml
Some directories do not exist on the custom layout. I.e. have a `null` variable. (The local tool path I believe). And these directories can not be created. Using a `when: item | default(False)` will prevent these `null` directories from being included and created (which causes a crash).
=> Only create paths if they exist

tasks/virtualenv.yml
When a python from conda is used, this step prevents errors during the dependency installation phase.
This addition is necessary to work with conda python.
=> Update setuptools as well as pip when creating a virtualenv.

defaults/main.yml, tasks/main.yml, templates/systemd/galaxy-reports.service.j2, templates/systemd/galaxy.service.j2
I also dropped the uWSGI stats port stuff - you can just set `stats: :port` in the `uwsgi` section of `galaxy.yml` to enable it if you want, and I didn't want to add more uWSGI-specific stuff to the role when we're deprecating uWSGI anyway.
=> Move systemd vars to individual vars to make them easier to override

README.md, defaults/main.yml, tasks/static_setup.yml
This is done in a way that should be fairly unobtrusive to people already specifying these configs via `galaxy_config_files`, `galaxy_config_templates`, and `galaxy_config.galaxy.*`.
For example, simply setting the new `galaxy_job_metrics_plugins` var in your vars will create `{{ galaxy_config_dir }}/job_metrics_conf.yml` with the var contents, and set the corresponding path option in `galaxy.yml` (unless overridden by explicitly setting `galaxy_config.galaxy.job_metrics_config_file`). The var syntax matches the Galaxy YAML plugin syntax (which we need to document and provide examples for by converting `job_metrics_conf.xml.sample`).
I believe all the following should be supportable via this mechanism since they all use the plugin config lib:
The Pulsar role has a syntax that is converted …
=> Support specification of ancillary configs in YAML

tasks/virtualenv.yml
At least in the k8s image building process, the newest setuptools is problematic due to them having dropped `use_2to3`.
`
error in attmap setup command: use_2to3 is invalid.
...
Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\nERROR: Could not find a version that satisfies the requirement attmap==0.12.11 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.10, 0.12.11, 0.13.0)\nERROR: No matching distribution found for attmap==0.12.11\n"}
`
Pinning it seems to fix the problem.
=> Pin setuptools

tasks/static_setup.yml
This PR enables the use of dynamic job rules as ansible templates, distinguishing from pure python setups.
=> Enable optional dynamic job rules as templates

tasks/static_setup.yml
Reverting the change I made in #141 to notify handlers restart when job rules are updated, as watch_job_rules is more comfortable
=> Job rules: no need to notify handlers resart if watch_job_rules is enabled

tasks/static_setup.yml
Reported by @abretaud in the comments of #135.
=> Fix sending dynamic rules files that do not end in .py

tasks/client.yml
I got this error from the subsequent yarn install (`npm install --global yarn`) step, however. Not sure if this is just me, but the error is pretty inscrutable for someone not deeply familiar with Node:
```
TypeError: Class extends value undefined is not a constructor or null
at Object.<anonymous> (/srv/galaxy/venv/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> …
```
=> Support updating Node when the pinned version changes

defaults/main.yml, tasks/dependencies.yml
For issue https://github.com/galaxyproject/ansible-galaxy/issues/140
The use case for Galaxy Australia is needing to install the `total-perspective-vortex` package into the venv after it has been created but before the restart handler runs.
=> variable `galaxy_additional_venv_packages` to install extra python packages in galaxy venv

tasks/database.yml
Fixes #151 
This will support both pre- and post-alembic versions. No change to galaxy core is required.
=> Check for both alembic and SQLAlchemy Migrate errors

tasks/static_setup.yml
The old syntax is no longer supported as of Ansible 2.13.
https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_6.html#playbook
=> Update syntax for list concatenation

tasks/virtualenv.yml
The dependencies that relied on `use_2to3` have been updated [1] and the changes in #139 are no longer necessary.
1. https://attmap.databio.org/en/latest/changelog/
=> Install latest setuptools

tasks/database.yml
Exception classes were moved into their own module in [#15509 (galaxy)](https://github.com/galaxyproject/galaxy/pull/15509/commits/df0c6b629243d4b897611d096423cfcee37d91e2).
=> Fix exception fully qualified name

.github/workflows/molecule.yml, defaults/main.yml, tasks/_inc_node_version.yml
=> Support defining a maximum node version for a given platform

tasks/dependencies.yml
This was only ever done as a convenience and is no longer needed or desirable with Gravity 1.0 (keeping it generally won't harm anything either, although it might cause confusion down the line).
=> Drop modifying venv activate to set `$GRAVITY_STATE_DIR`

tasks/mutable_setup.yml
Based on #188 and #189, mutable directories must be created by the privsep user, with galaxy_user:galaxy_group
=> Second attempt at fixing, must be privsep to create

defaults/main.yml, tasks/static_setup.yml
for e.g. welcome.html to be readable by nginx
=> Allow changing mode of static files

defaults/main.yml
Ubuntu 20.04 LTS has jinja2 2.10.1, which doesn't support `is true` and various other `is` tests added in https://github.com/pallets/jinja/pull/824
Fix:
```
TASK [galaxyproject.galaxy : Schedule tmpclean cron job (root)] *******************************************************************************************************************************************
fatal: [gat-18.eu.galaxy.training]: FAILED! => 
msg: |-
An unhandled exception occurred while templating '{{ (galaxy_tmpclean_log is not true) | ternary(
((galaxy_tmpclean_log is none) | ternary(
'>/dev/null',
'>>' ~ galaxy_tmpclean_log
)),
''
) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: no test named 'true'. String: {{ (galaxy_tmpclean_log is not true) | ternary( …
```
=> Fix issue with jinja2 < 2.11.0

defaults/main.yml, tasks/static_subdomain_dirs.yml
This is a small improvement for the copy tasks in the static directories
As the role currently works, the whole static directory is `rsync`ed into every new subdomain directory, which leads to additional disk usage of ~ 154 MB for each subdomain in a basic (GTN) Galaxy setup.
With this improvement, several static subdirectories are symlinked and all files inside `dist` are symlinked, which reduces the disk usage per subdomain to ~ 2.3 MB.
However the disadvantage of this is:
- more extensive logs; each symlink needs to be checked and is logged by ansible, around 200 per subdomain, the `galaxy_themes_no_symlink_logs` just reduces the extent, but ansible still prints one line per file and subdomain
- slightly slower playbook runs; `synchronize` for the whole folder is faster than invoking …
=> Symlinks reduce disk usage

templates/galaxy.yml.j2
I tested this with my test instance, but please check if there could be scenarios where we don't want to remove configuration keys with length = 0
I nominate this for the ugliest jinja2 solution
=> Fixes #200

README.md, tasks/static_setup.yml, templates/local_tool_conf.xml.j2
This alters the previous behavior slightly, tools that do not specify a section will be placed in a section named **Local Tools** whereas previously they would be outside of a section.
The old simple syntax is still supported:
```yaml
galaxy_local_tools:
- foo.xml
- bar.xml
```
Is the same as:
```yaml
galaxy_local_tools:
- file: foo.xml
section_name: Local Tools
- file: bar.xml
section_name: Local Tools
```
=> Support installing local tools into sections

README.md
Hi all,
I tried following the best practices guide in the README in the playbook I'm working on and noticed I had to deviate from it at some points. Maybe I did something wrong, but wanted to open this PR in case the best practice indeed needs to be updated. I'm pretty sure about the following changes:
* update to the postgres_objects role name
* `supervisorctl` should not be used
I needed to add the `systemd` `post_tasks` to actually get Galaxy to start up the first time, but maybe there's a better way for this?
=> Update best practice in README.md

molecule/default/converge.yml, templates/systemd/galaxy.service.j2
I noticed the reason why the molecule runs for version `23.0` were failing was that `supervisord` was attempting to run Galaxy with the wrong config file. On the failing containers, `/srv/galaxy/var/gravity/supervisor/supervisord.conf.d/_default_.d/galaxy_gunicorn_gunicorn.conf` has:
```
command         = /srv/galaxy/venv/bin/galaxyctl --config-file /srv/galaxy/server/config/galaxy.yml.sample exec _default_ gunicorn
```
It looks like this is because the systemd unit file doesn't correctly set the `GRAVITY_CONFIG_FILE` environment variable.
Additionally, I locally ran into some issues requiring further `apt` dependencies to be installed on Ubuntu in order for some of Galaxy's dependencies to compile correctly. This does not seem to have lead to test failures on CI, my hunch is that this …
=> Add GRAVITY_CONFIG_FILE to systemd env

.github/workflows/molecule.yml, defaults/main.yml, molecule/_common/_inc_pre_tasks.yml, molecule/prebuilt_client/converge.yml, molecule/prebuilt_client/molecule.yml, molecule/prebuilt_client/verify.yml, tasks/_inc_client_install_tools.yml, tasks/client.yml
Resolves #207
This PR:
1. Adds optional support for deploying the prebuilt client in `client.yml`.
2. Splits up the installation of node and yarn into a new includes file so that it can be used in both strategies (prebuilt and build).
3. Adds a molecule scenario to test the prebuilt client, refactoring the `pre_tasks` from the default scenario into a separate file.
=> Support prebuilt client

README.md, defaults/main.yml, tasks/themes.yml
This way the role does not modify files in the playbook, and moves in line with other recent changes to move more of Galaxy's extraneous configs into structured data.
@mira-miracoli if you approve I'll update the documentation.
=> Make themes structured data instead of read from file

tasks/themes.yml
Especially important for the non-subdomain theme since order is significant (the first one in `themes_conf.yml` is the default).
=> Maintain theme dict ordering on write

templates/welcome.html.j2
During a fresh deployment, I find that not having the changes proposed in this PR leads to the following error,
```
2025-07-21 14:36:05,725 p=183333 u=sanjay n=ansible | TASK [galaxyproject.galaxy : Template welcome.html for basedomain] ***************************************************************************************************************************************************************************************************
2025-07-21 14:36:06,182 p=183333 u=sanjay n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'subdomain' is undefined. 'subdomain' is undefined
2025-07-21 14:36:06,183 p=183333 u=sanjay n=ansible | fatal: [sn09.galaxyproject.eu]: FAILED! => changed=false 
msg: …
```
=> Update welcome.html.j2 with additional check to ensure that subdomain variable is defined
